title: Jamil RAIS-ALI

logo: /profile.jpg

description: >
  Economics • Data Analytics • Sustainability / ESG
  Data Analyst | Risk Analyst | ESG Analyst | Business Analyst

theme: jekyll-theme-minimal

show_downloads: false
